import React, { useEffect, useRef, useState, useCallback } from "react";
import { Eye, EyeOff, Loader2, Maximize2 } from "lucide-react";
import { getOrbitalCube } from "../api/client";

// Atom colors (CPK convention)
const ATOM_COLORS = {
  H: 0xffffff, C: 0x222222, N: 0x3050f8, O: 0xff0d0d, F: 0x90e050,
  P: 0xff8000, S: 0xffff30, Cl: 0x1ff01f, Br: 0xa62929, I: 0x940094,
  default: 0xffaaaa,
};

const ISOVALUE_DEFAULT = 0.04;

export default function MolecularViewer({ atoms, calcId, orbitals, homoIdx }) {
  const containerRef = useRef(null);
  const viewerRef = useRef(null);
  const [isLoading, setIsLoading] = useState(false);
  const [loadingOrb, setLoadingOrb] = useState(null);
  const [activeOrbIdx, setActiveOrbIdx] = useState(null);
  const [isovalue, setIsovalue] = useState(ISOVALUE_DEFAULT);
  const [showPositive, setShowPositive] = useState(true);
  const [showNegative, setShowNegative] = useState(true);
  const [error, setError] = useState(null);
  const [viewerReady, setViewerReady] = useState(false);

  // Initialize 3Dmol viewer
  useEffect(() => {
    if (!containerRef.current) return;

    let $3Dmol;
    try {
      $3Dmol = require("3dmol");
    } catch {
      setError("3Dmol.js not available. Install with: npm install 3dmol");
      return;
    }

    const viewer = $3Dmol.createViewer(containerRef.current, {
      backgroundColor: "0x0a0e1a",
      antialias: true,
    });

    viewerRef.current = viewer;
    setViewerReady(true);

    return () => {
      try { viewer.clear(); } catch {}
    };
  }, []);

  // Render molecule when atoms change
  useEffect(() => {
    if (!viewerReady || !viewerRef.current || !atoms || atoms.length === 0) return;

    const viewer = viewerRef.current;
    viewer.clear();

    // Build XYZ string for 3Dmol
    const xyz = `${atoms.length}\nGenerated by HF-SCF Calculator\n` +
      atoms.map((a) => `${a.symbol} ${a.x.toFixed(6)} ${a.y.toFixed(6)} ${a.z.toFixed(6)}`).join("\n");

    viewer.addModel(xyz, "xyz");
    viewer.setStyle({}, {
      stick: { radius: 0.12, colorscheme: "Jmol" },
      sphere: { scale: 0.3, colorscheme: "Jmol" },
    });
    viewer.zoomTo();
    viewer.render();
    setActiveOrbIdx(null);
    setError(null);
  }, [atoms, viewerReady]);

  const loadOrbital = useCallback(async (orbIdx) => {
    if (!viewerRef.current || !calcId) return;
    setIsLoading(true);
    setLoadingOrb(orbIdx);
    setError(null);

    try {
      const cubeData = await getOrbitalCube(calcId, orbIdx, 60, 60, 60);
      const viewer = viewerRef.current;

      // Remove previous volumetric surfaces
      viewer.removeAllShapes();
      // Keep the molecule model but re-add surfaces
      const models = viewer.getModel();

      const vol = viewer.addVolumetricData(cubeData, "cube", {
        isoval: isovalue,
        color: "blue",
        opacity: 0.75,
        wireframe: false,
        smoothness: 5,
      });

      // Add negative lobe
      const volNeg = viewer.addVolumetricData(cubeData, "cube", {
        isoval: -isovalue,
        color: "red",
        opacity: 0.75,
        wireframe: false,
        smoothness: 5,
      });

      if (vol) vol.setVisible(showPositive);
      if (volNeg) volNeg.setVisible(showNegative);

      viewer.render();
      setActiveOrbIdx(orbIdx);
    } catch (e) {
      setError(e.message || "Failed to load orbital");
    } finally {
      setIsLoading(false);
      setLoadingOrb(null);
    }
  }, [calcId, isovalue, showPositive, showNegative]);

  const clearOrbitals = () => {
    if (!viewerRef.current) return;
    viewerRef.current.removeAllShapes();
    viewerRef.current.render();
    setActiveOrbIdx(null);
  };

  // Visible orbital list: HOMO-3 through LUMO+3
  const displayOrbitals = orbitals
    ? orbitals.filter((o) => {
        const diff = o.index - homoIdx;
        return diff >= -3 && diff <= 3;
      })
    : [];

  return (
    <div className="card space-y-3">
      <h2 className="text-slate-100 font-semibold text-sm flex items-center gap-2">
        <Eye size={16} className="text-green-400" />
        3D Molecular Viewer
      </h2>

      {/* Viewer canvas */}
      <div className="mol-viewer-container" ref={containerRef}>
        {(!atoms || atoms.length === 0) && (
          <div className="absolute inset-0 flex items-center justify-center text-slate-600 text-sm">
            Run a calculation to view the molecule
          </div>
        )}
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/50 rounded-xl z-10">
            <div className="flex items-center gap-2 text-slate-300">
              <Loader2 size={20} className="animate-spin text-blue-400" />
              <span className="text-sm">Generating orbital cube...</span>
            </div>
          </div>
        )}
      </div>

      {error && (
        <p className="text-red-400 text-xs bg-red-950/30 border border-red-800 rounded-lg px-3 py-2">
          {error}
        </p>
      )}

      {/* Orbital selector */}
      {displayOrbitals.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="label mb-0">Molecular Orbitals</span>
            {activeOrbIdx !== null && (
              <button className="btn-secondary text-xs flex items-center gap-1" onClick={clearOrbitals}>
                <EyeOff size={12} /> Clear
              </button>
            )}
          </div>
          <div className="grid grid-cols-4 gap-1">
            {displayOrbitals.map((orb) => {
              const isHomo = orb.label === "HOMO";
              const isLumo = orb.label === "LUMO";
              const isActive = activeOrbIdx === orb.index;
              return (
                <button
                  key={orb.index}
                  disabled={isLoading}
                  onClick={() => isActive ? clearOrbitals() : loadOrbital(orb.index)}
                  className={`px-2 py-1.5 rounded-lg text-xs font-semibold border transition-colors
                    ${isActive
                      ? isHomo ? "bg-blue-700 border-blue-500 text-white"
                        : isLumo ? "bg-purple-700 border-purple-500 text-white"
                        : "bg-slate-600 border-slate-400 text-white"
                      : isHomo ? "bg-blue-950/40 border-blue-800 text-blue-300 hover:border-blue-600"
                        : isLumo ? "bg-purple-950/40 border-purple-800 text-purple-300 hover:border-purple-600"
                        : "bg-slate-800 border-slate-700 text-slate-400 hover:border-slate-500"
                    } ${isLoading && loadingOrb === orb.index ? "animate-pulse" : ""}`}
                >
                  {orb.label}
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Isosurface controls */}
      {activeOrbIdx !== null && (
        <div className="bg-slate-800/50 rounded-lg p-3 space-y-2 border border-slate-700">
          <div className="flex items-center justify-between">
            <span className="text-xs text-slate-400 font-semibold">Isosurface Controls</span>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-slate-400">Isovalue: {isovalue.toFixed(3)}</span>
            </div>
            <input
              type="range" min="0.005" max="0.15" step="0.005"
              value={isovalue}
              onChange={(e) => setIsovalue(parseFloat(e.target.value))}
              className="w-full accent-blue-500"
            />
          </div>
          <div className="flex gap-3">
            <label className="flex items-center gap-1.5 text-xs text-slate-300 cursor-pointer">
              <input
                type="checkbox" checked={showPositive}
                onChange={(e) => setShowPositive(e.target.checked)}
                className="accent-blue-500"
              />
              <span className="w-3 h-3 rounded-sm bg-blue-500 inline-block" />
              +phase
            </label>
            <label className="flex items-center gap-1.5 text-xs text-slate-300 cursor-pointer">
              <input
                type="checkbox" checked={showNegative}
                onChange={(e) => setShowNegative(e.target.checked)}
                className="accent-red-500"
              />
              <span className="w-3 h-3 rounded-sm bg-red-500 inline-block" />
              −phase
            </label>
          </div>
        </div>
      )}
    </div>
  );
}
