"""Wind field: steady uniform wind + MIL-F-8785C Dryden turbulence.

Dryden model
------------
The Dryden spectra are defined here as *one-sided* power spectral densities in
the spatial frequency ``Omega`` [rad/m], normalised so that
``integral_0^inf Phi(Omega) dOmega = sigma^2``:

    Phi_u(Omega) = sigma_u^2 * (2 L_u / pi) / (1 + (L_u Omega)^2)

    Phi_v(Omega) = sigma_v^2 * (L_v / pi) * (1 + 3 (L_v Omega)^2)
                                          / (1 + (L_v Omega)^2)^2

    Phi_w(Omega) = sigma_w^2 * (L_w / pi) * (1 + 3 (L_w Omega)^2)
                                          / (1 + (L_w Omega)^2)^2

This is the MIL-F-8785C form written with the scale-length convention in which
the transverse numerator carries ``sqrt(3)`` (equivalently the commonly quoted
``(1 + 12 L^2 Omega^2)/(1 + 4 L^2 Omega^2)^2`` form with ``L -> 2L``).  Under
Taylor's frozen-turbulence hypothesis a vehicle flying at airspeed ``V`` sees
the temporal spectrum ``G(omega) = Phi(omega / V) / V`` [ (m/s)^2 / (rad/s) ].

Shaping filters
---------------
The realisations are generated by driving unit-intensity white noise through

    H_u(s) = k_u / (1 + tau_u s)
    H_v(s) = k_v (1 + sqrt(3) tau_v s) / (1 + tau_v s)^2
    H_w(s) = k_w (1 + sqrt(3) tau_w s) / (1 + tau_w s)^2       tau = L / V

whose squared magnitudes reproduce the shapes above exactly.  Rather than
quoting a textbook gain (whose normalisation depends on a one-sided/two-sided
convention), ``k`` is fixed here by solving the continuous Lyapunov equation
``A P + P A^T + B B^T = 0`` and scaling ``C`` so that the stationary output
variance ``C P C^T`` is exactly ``sigma^2``.  Because the filter fixes the
*shape* and the Lyapunov scaling fixes the *area*, the realised spectrum equals
the analytic Dryden spectrum.

Sampling is exact (not Euler): the filter states are propagated with the van
Loan discretisation

    A_d = expm(A dt),  Q_d = int_0^dt expm(A s) B B^T expm(A^T s) ds,

and initialised from the stationary covariance ``P`` so there is no warm-up
transient.

Assumptions
-----------
* The filter time constants are frozen at the nominal cruise airspeed, which
  keeps the process linear time-invariant (and therefore exactly testable
  against the analytic PSD).  Airspeed excursions in these scenarios are a few
  percent, so the induced scale error is small.
* Each vehicle carries an independent turbulence realisation; spatial
  correlation of the gust field between vehicles is **not** modelled.
* Gusts enter kinematically as an additive wind vector; gust-induced
  aerodynamic transients (e.g. the roll moment from a gust gradient across the
  span) are not modelled.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np
from scipy.linalg import expm, solve_continuous_lyapunov

from .config import DrydenParams, WindParams

SQRT3 = float(np.sqrt(3.0))


# --------------------------------------------------------------------------
# Analytic spectra
# --------------------------------------------------------------------------
def dryden_psd_spatial(omega_spatial: np.ndarray, sigma: float, L: float,
                       component: str) -> np.ndarray:
    """One-sided Dryden PSD in spatial frequency [ (m/s)^2 / (rad/m) ]."""
    Om = np.asarray(omega_spatial, dtype=float)
    x2 = (L * Om) ** 2
    if component == "u":
        return sigma ** 2 * (2.0 * L / np.pi) / (1.0 + x2)
    if component in ("v", "w"):
        return sigma ** 2 * (L / np.pi) * (1.0 + 3.0 * x2) / (1.0 + x2) ** 2
    raise ValueError(f"unknown component {component!r}")


def dryden_psd_temporal(omega: np.ndarray, sigma: float, L: float, V: float,
                        component: str) -> np.ndarray:
    """One-sided Dryden PSD in temporal frequency [ (m/s)^2 / (rad/s) ]."""
    omega = np.asarray(omega, dtype=float)
    return dryden_psd_spatial(omega / V, sigma, L, component) / V


# --------------------------------------------------------------------------
# Shaping filters
# --------------------------------------------------------------------------
def _first_order_ss(sigma: float, tau: float):
    A = np.array([[-1.0 / tau]])
    B = np.array([[1.0]])
    C = np.array([[1.0]])
    return _normalise(A, B, C, sigma)


def _second_order_ss(sigma: float, tau: float):
    # H(s) = k (1 + sqrt3 tau s) / (1 + tau s)^2
    A = np.array([[0.0, 1.0], [-1.0 / tau ** 2, -2.0 / tau]])
    B = np.array([[0.0], [1.0]])
    C = np.array([[1.0, SQRT3 * tau]])
    return _normalise(A, B, C, sigma)


def _normalise(A, B, C, sigma):
    """Scale C so that the stationary output variance equals sigma^2."""
    # A P + P A^T + B B^T = 0  ->  solve_continuous_lyapunov(A, -Q)
    P = solve_continuous_lyapunov(A, -(B @ B.T))
    var = float((C @ P @ C.T).item())
    C = C * (sigma / np.sqrt(var))
    return A, B, C, P


def _van_loan(A, B, dt):
    n = A.shape[0]
    M = np.zeros((2 * n, 2 * n))
    M[:n, :n] = -A
    M[:n, n:] = B @ B.T
    M[n:, n:] = A.T
    F = expm(M * dt)
    Ad = F[n:, n:].T
    Qd = Ad @ F[:n, n:]
    Qd = 0.5 * (Qd + Qd.T)
    return Ad, Qd


class _Channel:
    """One exactly-sampled Dryden channel, replicated over ``n`` vehicles."""

    def __init__(self, sigma, L, V, dt, order, n, rng):
        tau = L / V
        if order == 1:
            A, B, C, P = _first_order_ss(sigma, tau)
        else:
            A, B, C, P = _second_order_ss(sigma, tau)
        self.A, self.B, self.C, self.P = A, B, C, P
        self.Ad, self.Qd = _van_loan(A, B, dt)
        # Cholesky of Qd (may be near-singular for tiny dt -> add jitter).
        try:
            self.Lq = np.linalg.cholesky(self.Qd)
        except np.linalg.LinAlgError:
            w, Vq = np.linalg.eigh(self.Qd)
            self.Lq = Vq @ np.diag(np.sqrt(np.maximum(w, 0.0)))
        # Stationary initial condition.
        try:
            Lp = np.linalg.cholesky(self.P)
        except np.linalg.LinAlgError:
            w, Vp = np.linalg.eigh(self.P)
            Lp = Vp @ np.diag(np.sqrt(np.maximum(w, 0.0)))
        self.dim = A.shape[0]
        self.x = rng.standard_normal((n, self.dim)) @ Lp.T
        self.rng = rng

    def step(self) -> np.ndarray:
        n = self.x.shape[0]
        w = self.rng.standard_normal((n, self.dim)) @ self.Lq.T
        self.x = self.x @ self.Ad.T + w
        return self.x @ self.C.ravel()


class DrydenTurbulence:
    """Vectorised Dryden gust generator: u (along-track), v (cross), w (vertical)."""

    def __init__(self, params: DrydenParams, V: float, dt: float, n: int,
                 rng: np.random.Generator):
        self.params = params
        self.V = V
        self.dt = dt
        self.n = n
        self.cu = _Channel(params.sigma_u, params.L_u, V, dt, 1, n, rng)
        self.cv = _Channel(params.sigma_v, params.L_v, V, dt, 2, n, rng)
        self.cw = _Channel(params.sigma_w, params.L_w, V, dt, 2, n, rng)

    def step(self) -> np.ndarray:
        """Advance one ``dt`` and return gusts (n, 3) in wind axes (u, v, w)."""
        return np.stack([self.cu.step(), self.cv.step(), self.cw.step()], axis=1)


def dryden_series(params: DrydenParams, V: float, dt: float, n_samples: int,
                  component: str, rng: np.random.Generator) -> np.ndarray:
    """Generate a single long scalar Dryden realisation (for PSD validation)."""
    sigma = {"u": params.sigma_u, "v": params.sigma_v, "w": params.sigma_w}[component]
    L = {"u": params.L_u, "v": params.L_v, "w": params.L_w}[component]
    order = 1 if component == "u" else 2
    ch = _Channel(sigma, L, V, dt, order, 1, rng)
    out = np.empty(n_samples)
    for i in range(n_samples):
        out[i] = ch.step()[0]
    return out


# --------------------------------------------------------------------------
# Full wind field
# --------------------------------------------------------------------------
class WindField:
    """Steady uniform mean wind plus per-vehicle Dryden turbulence."""

    def __init__(self, params: WindParams, n_vehicles: int, V_nom: float,
                 dt: float, rng: np.random.Generator):
        self.params = params
        self.mean = np.asarray(params.mean, dtype=float)
        self.n = n_vehicles
        self._turb = None
        if params.turbulence_on:
            self._turb = DrydenTurbulence(params.dryden, V_nom, dt, n_vehicles, rng)
        self._gust_enu = np.zeros((n_vehicles, 3))

    def step(self, psi: np.ndarray) -> None:
        """Advance the turbulence state; ``psi`` is the per-vehicle heading."""
        if self._turb is None:
            return
        g = self._turb.step()          # (n, 3) in (along, cross, vertical)
        c, s = np.cos(psi), np.sin(psi)
        # along-track unit vector (c, s, 0); cross-track (-s, c, 0); vertical (0,0,1)
        self._gust_enu[:, 0] = g[:, 0] * c - g[:, 1] * s
        self._gust_enu[:, 1] = g[:, 0] * s + g[:, 1] * c
        self._gust_enu[:, 2] = g[:, 2]

    def wind(self) -> np.ndarray:
        """Current ENU wind at each vehicle, shape (n, 3)."""
        return self.mean[None, :] + self._gust_enu

    @property
    def gust(self) -> np.ndarray:
        return self._gust_enu


def dryden_series_batch(params: DrydenParams, V: float, dt: float,
                        n_samples: int, n_realisations: int, component: str,
                        rng: np.random.Generator) -> np.ndarray:
    """Generate ``n_realisations`` independent Dryden realisations.

    Returns an array of shape ``(n_realisations, n_samples)``.  Averaging
    periodograms over independent realisations is what makes the PSD check
    tight without needing an enormous single record.
    """
    sigma = {"u": params.sigma_u, "v": params.sigma_v, "w": params.sigma_w}[component]
    L = {"u": params.L_u, "v": params.L_v, "w": params.L_w}[component]
    order = 1 if component == "u" else 2
    ch = _Channel(sigma, L, V, dt, order, n_realisations, rng)
    out = np.empty((n_samples, n_realisations))
    for i in range(n_samples):
        out[i] = ch.step()
    return out.T
